### ISSUE TITLE
Не работает в FireFox

### ISSUE THREAD

**Issue by Newbilius** [xoposhiy/firebase-course#1]
Не работает в FireFox 50.0.1 - самом свежем на момент написания этого текста.
Все слова и фразы в тесте некликабельны. Получаю ошибку на каждый клик:

`TypeError: e.srcElement is undefined`

**Comment by xoposhiy** [comment]
Ага, этот баг я исправил после прогона МК, но задеплоить исправленную версию забыл. Только что задеплоил. Должно исправиться.
